### ISSUE TITLE
Glow Effects sometimes overlapped with action button glow effects

### ISSUE THREAD

**Issue by hobulian** [casualshammy/NameplateAuras#144] opened 2022-02-14 04:29 UTC
**Describe the bug**
It's not lua error but, sometimes glow effects overlapped with button glow effects. So some auras has dual glows.

**To Reproduce**
I am using some taunt spells with action button glow and pixel glow on covenant debuffs like soul rot(warlock fae spell). And sometimes button glows overlapped with mysterious action button glow. Even when i setted action button glow for spells other action button glows shown up and aura has double action button glows.

**Screenshots**
https://imgur.com/a/LC3S7jh
https://imgur.com/a/xOMdAji

**Video**
https://www.youtube.com/watch?v=BT9TzL4as9Q

**Comment by hobulian** [comment] 2022-02-14 15:05
First i thought it was due to nameplate number like nameplate1~40 but, I think it's about aura's order. I setted every auras it's size and sort by it's sizes.
![image](https://user-images.githubusercontent.com/26172440/153889145-59284691-0e77-4abb-89d5-895fade7794b.png)
So when glowing aura changes it's position due to new auras applied or some applied auras removed this happened.

**Comment by casualshammy** [comment] 2022-02-15 17:30
Hello!
I hope this issue got fixed in the latest release (90105.15-release). I'll appreciate if you'll try it out.

**Comment by hobulian** [comment] 2022-02-16 08:57
![image](https://user-images.githubusercontent.com/26172440/154230002-0512d9d8-e62c-4542-b802-3c34f61f68ee.png)
Still same i think. Might had to add hide strings to aura_removed or nameplate_unit_removed

**Comment by casualshammy** [comment] 2022-02-16 16:12
Unfortunately, I can't reproduce this bug currently:
![NAuras_144](https://user-images.githubusercontent.com/4965168/154307467-335c583c-1f41-4a45-8283-ad7c70eb14b8.gif)

**Comment by hobulian** [comment] 2022-02-17 00:29
![image](https://user-images.githubusercontent.com/26172440/154380525-c6ade5a9-4b10-4c66-aa68-561cd9dd25e0.png)
I don't know this time. How i reproduce this one. But sure it double glows now with some conditions.

**Comment by hobulian** [comment] 2022-02-17 00:43
https://www.youtube.com/watch?v=9IyAcGpm-LM&ab_channel=%EC%A0%84%EC%9A%B0%EC%A7%84

I made video for this one. Recorded right after reloading client.

**Comment by casualshammy** [comment] 2022-02-27 17:06
> https://www.youtube.com/watch?v=9IyAcGpm-LM&ab_channel=%EC%A0%84%EC%9A%B0%EC%A7%84
> 
> I made video for this one. Recorded right after reloading client.

Do you mean stuck animation in the last seconds of video? It looks like a bug in `LibButtonGlow` library or bug in Blizzard's glow animation. I'll try to update this lib and then post an update here.

**Closed as completed** 2022-10-08 17:00 UTC
Labels: type: bug, status: confirmed
