### ISSUE TITLE
Desription goes off screen

### ISSUE THREAD

**Issue by mahveenya1991** [casualshammy/NameplateAuras#50] opened 2020-06-18 21:12 UTC
Hello!

First of all I want to thank you for this brilliant addon, its very cool.
What i recently have found is that the description of my physically situated items higher goes off screen and I cannot see them. See screenshot further.
I did not thoght that this could be NameplateAuras but when  I have disabled it - issue did not reproduced. 
So basically during dungeon/raid/BG something is happening and description goes off screen
And until /reload I cannot see it.

Please, can you help me with this? 

![image](https://user-images.githubusercontent.com/67125066/85072277-7fd9b500-b1c1-11ea-9a07-3a1246151c37.png)

This is how it looks like when all good or after reload:

![image](https://user-images.githubusercontent.com/67125066/85072371-b0b9ea00-b1c1-11ea-9339-e066718ab944.png)

**Comment by casualshammy** [comment] 2020-06-19 07:13
Hello.
Are you using TinyTooltip addon? #39

**Comment by puttputt** [comment] 2020-07-13 02:01
I can confirm this issue is also happening to me.

It looks like the issue is when "Show aura name when mouse is over auras icon" is selected.

Unfortunately I don't know how to see the error log sothats all I can provide.

**Comment by mahveenya1991** [comment] 2020-07-14 19:52
thanks anyway dude! I will try without this option

пн, 13 июл. 2020 г. в 05:01, Kyle Smyth <notifications@github.com>:

**Comment by casualshammy** [comment] 2020-08-09 10:09
Fixed in 80300.4-release

**Closed** 2020-08-11 17:16 UTC
Labels: bug

**Comment by mahveenya1991** [comment] 2020-08-13 18:41
Hi yes but now cannot play retail since my PC was stolen :((

I will come back in SEPT and can update you regarding this issue.


пт, 19 июн. 2020 г. в 10:13, casualshammy <notifications@github.com>:
